# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 15:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microblog_web', '0002_auto_20161227_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='microblog_web.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='displayName',
            field=models.CharField(default='makaka', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(default='', max_length=150),
        ),
    ]
