# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-07 20:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microblog_web', '0004_auto_20170107_1915'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='post_hashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microblog_web.Hashtag')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='microblog_web.Post')),
            ],
        ),
    ]
