# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog_web', '0006_auto_20170108_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_hashtag',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
