# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-10 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog_web', '0007_post_hashtag_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='post_hashtag',
            name='hashtag',
        ),
        migrations.RemoveField(
            model_name='post_hashtag',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='hashtags',
            field=models.ManyToManyField(to='microblog_web.Hashtag'),
        ),
        migrations.AddField(
            model_name='profile',
            name='following',
            field=models.ManyToManyField(related_name='_profile_following_+', to='microblog_web.Profile'),
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
        migrations.DeleteModel(
            name='post_hashtag',
        ),
    ]
