# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog_web', '0008_auto_20170110_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location_lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='location_lon',
            field=models.DecimalField(decimal_places=6, max_digits=9, null=True),
        ),
    ]
