# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import microblog_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog_web', '0009_auto_20170111_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to=microblog_web.models.user_directory_path)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='coverImage',
            field=models.FileField(default='settings.STATIC_ROOT/microblog/img/cover-image.jpg', upload_to=microblog_web.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.FileField(default='settings.STATIC_ROOT/microblog/img/profile-image.jpg', upload_to=microblog_web.models.user_directory_path),
        ),
    ]
