# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-11 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import microblog_web.models


class Migration(migrations.Migration):

    dependencies = [
        ('microblog_web', '0014_auto_20170111_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coverImage',
            field=models.FileField(default='default/img/cover-image.jpg', upload_to=microblog_web.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.FileField(default='default/img/profile-image.jpg', upload_to=microblog_web.models.user_directory_path),
        ),
    ]
